---
title: "Resume/CV"
---
  

# Anisah Calvin Cuevas

anisah@ucsb.edu - anisahc2000.3@gmail.com - 626 364 8582


### **Education**


#### *University of California - Santa Barbara / December 2021*

- B.A. in Geography - Emphasis in Geographic Information Science

- Cumulative GPA: 3.23

- Relevant Coursework:
  - Physical Geography, General Chemistry, Linear Algebra, Statistics,      Human Geography, California Architecture, Geography of California,      Health Geography, Location Theory & Modeling, Cartography, GIS          Programming
  
  
#### *Charter Oak High School - Covina, CA / June 2018*

- High School Diploma

- Cumulative GPA: 4.2

### **Experience**

#### *Associated Students UCSB - Santa Barbara, CA*

- AS Administration

  - Student Office Manager / April 2019 - Present

#### *UC Santa Barbara Library - Santa Barbara, CA*

- Special Research Collections - Maps and Aerial Photos

  - Student Assistant / April 2019 - Present
  
#### *Cutco Closing Gifts - Azusa, CA*

- Project Manager / June 2018 - December 2018


### **Organizations and Associations**

#### *Alpha Delta Pi*

- Gamma Xi Chapter at UC Santa Barbara


